export const OPEN_SURVEY_TABLE_ROW = "OPER_SURVEY_TABLE_ROW";
export const CHECK_SURVEY_TABLE_ROW = "CHECK_SURVEY_TABLE_ROW";
export const CHECK_ALL_SURVEY_TABLE_ROWS = "CHECK_ALL_SURVEY_TABLE_ROWS";
export const SORT_SURVEYS = "SORT_SURVEYS";
